import oracledb
import os
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

# Admin credentials
ADMIN_USER = 'system'
ADMIN_PASSWORD = 'system' # As provided
DSN = os.getenv('ORACLE_DSN', 'localhost:1521/XEPDB1')

# App User credentials
APP_USER = os.getenv('ORACLE_USER', 'onboarding_user')
APP_PASSWORD = os.getenv('ORACLE_PASSWORD', 'onboarding123')

def setup_database():
    try:


        print(f"Connecting as app user ({APP_USER}) to create tables...")
        app_conn = oracledb.connect(user=APP_USER, password=APP_PASSWORD, dsn=DSN)
        app_cursor = app_conn.cursor()


        tables_sql = [
            """
            CREATE TABLE USERS (
                user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                email VARCHAR2(150) UNIQUE NOT NULL,
                password_hash VARCHAR2(255) NOT NULL,
                role VARCHAR2(20) DEFAULT 'new_hire',
                department_id NUMBER,
                joining_date DATE,
                is_active NUMBER(1) DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """,
            """
            CREATE TABLE DEPARTMENTS (
                department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                description VARCHAR2(255),
                head_user_id NUMBER
            )
            """,
            """
            ALTER TABLE USERS ADD CONSTRAINT fk_user_dept FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(department_id)
            """,
            """
            ALTER TABLE DEPARTMENTS ADD CONSTRAINT fk_dept_head FOREIGN KEY (head_user_id) REFERENCES USERS(user_id)
            """,
            """
            CREATE TABLE ONBOARDING_TASKS (
                task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR2(200) NOT NULL,
                description CLOB,
                category VARCHAR2(50) NOT NULL,
                default_due_days NUMBER DEFAULT 7,
                is_mandatory NUMBER(1) DEFAULT 1,
                department_id NUMBER REFERENCES DEPARTMENTS(department_id)
            )
            """,
            """
            CREATE TABLE TASK_ASSIGNMENTS (
                assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                task_id NUMBER REFERENCES ONBOARDING_TASKS(task_id),
                user_id NUMBER REFERENCES USERS(user_id),
                status VARCHAR2(20) DEFAULT 'Pending',
                due_date DATE NOT NULL,
                completed_at TIMESTAMP,
                notes VARCHAR2(300)
            )
            """,
            """
            CREATE TABLE DOCUMENTS (
                doc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER REFERENCES USERS(user_id),
                doc_type VARCHAR2(100) NOT NULL,
                file_path VARCHAR2(500) NOT NULL,
                status VARCHAR2(20) DEFAULT 'Pending',
                reviewed_by NUMBER REFERENCES USERS(user_id),
                rejection_reason VARCHAR2(300),
                uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                reviewed_at TIMESTAMP
            )
            """,
            """
            CREATE TABLE ASSETS (
                asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                serial_number VARCHAR2(100) UNIQUE,
                category VARCHAR2(50) NOT NULL,
                condition VARCHAR2(20) DEFAULT 'Good',
                status VARCHAR2(20) DEFAULT 'Available',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """,
            """
            CREATE TABLE ASSET_ASSIGNMENTS (
                aa_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                asset_id NUMBER REFERENCES ASSETS(asset_id),
                user_id NUMBER REFERENCES USERS(user_id),
                assigned_by NUMBER REFERENCES USERS(user_id),
                assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                confirmed_at TIMESTAMP,
                returned_at TIMESTAMP
            )
            """,
            """
            CREATE TABLE TRAININGS (
                training_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR2(200) NOT NULL,
                description VARCHAR2(500),
                duration_hours NUMBER(4,1) NOT NULL,
                resource_url VARCHAR2(500),
                is_mandatory NUMBER(1) DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """,
            """
            CREATE TABLE TRAINING_ASSIGNMENTS (
                ta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                training_id NUMBER REFERENCES TRAININGS(training_id),
                user_id NUMBER REFERENCES USERS(user_id),
                status VARCHAR2(20) DEFAULT 'Pending',
                assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                completed_at TIMESTAMP
            )
            """,
            """
            CREATE TABLE BUDDIES (
                buddy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                new_hire_id NUMBER REFERENCES USERS(user_id),
                buddy_user_id NUMBER REFERENCES USERS(user_id),
                assigned_by NUMBER REFERENCES USERS(user_id),
                assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                is_active NUMBER(1) DEFAULT 1
            )
            """,
            """
            CREATE TABLE BUDDY_CHECKINS (
                checkin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                buddy_id NUMBER REFERENCES BUDDIES(buddy_id),
                notes CLOB NOT NULL,
                checkin_date DATE NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """,
            """
            CREATE TABLE ONBOARDING_FAQS (
                faq_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question VARCHAR2(500) NOT NULL,
                answer CLOB NOT NULL,
                category VARCHAR2(100),
                keywords VARCHAR2(300)
            )
            """
        ]

        for sql in tables_sql:
            print(f"Executing: {sql.strip().splitlines()[0][:50]}...")
            app_cursor.execute(sql)

        # Seed data
        print("Inserting seed data...")
        app_cursor.execute("INSERT INTO DEPARTMENTS (department_id, name, description) VALUES (1, 'Engineering', 'Tech & Dev teams')")
        app_cursor.execute("INSERT INTO DEPARTMENTS (department_id, name, description) VALUES (2, 'HR', 'Human Resources')")
        app_cursor.execute("INSERT INTO DEPARTMENTS (department_id, name, description) VALUES (3, 'Finance', 'Finance & Accounts')")
        
        # Admin user (bcrypt hash for 'admin123' is '$2b$12$6/7/L1.Qv/gN7yO.H.1/V.oVlR40oZ24N2P39i5C.QjY9N7L4tYh6')
        app_cursor.execute("INSERT INTO USERS (user_id, name, email, password_hash, role, department_id, joining_date) VALUES (1, 'Admin User', 'hr_admin@company.com', '$2b$12$6/7/L1.Qv/gN7yO.H.1/V.oVlR40oZ24N2P39i5C.QjY9N7L4tYh6', 'hr_admin', 2, CURRENT_DATE)")
        
        app_cursor.execute("INSERT INTO ONBOARDING_TASKS (title, category, default_due_days, is_mandatory) VALUES ('Submit Aadhaar & PAN Card', 'Document', 2, 1)")
        app_cursor.execute("INSERT INTO ONBOARDING_TASKS (title, category, default_due_days, is_mandatory) VALUES ('Collect Laptop from IT', 'IT Setup', 1, 1)")
        app_cursor.execute("INSERT INTO ONBOARDING_TASKS (title, category, default_due_days, is_mandatory) VALUES ('Complete Security Awareness Training', 'Training', 5, 1)")
        app_cursor.execute("INSERT INTO ONBOARDING_TASKS (title, category, default_due_days, is_mandatory) VALUES ('Read and Sign Code of Conduct', 'Policy', 3, 1)")
        app_cursor.execute("INSERT INTO ONBOARDING_TASKS (title, category, default_due_days, is_mandatory) VALUES ('Set Up Corporate Email', 'IT Setup', 1, 1)")

        app_cursor.execute("INSERT INTO TRAININGS (title, description, duration_hours, resource_url, is_mandatory) VALUES ('Code of Conduct', 'Company ethics and behaviour policy', 1, 'http://lms/coc', 1)")
        app_cursor.execute("INSERT INTO TRAININGS (title, description, duration_hours, resource_url, is_mandatory) VALUES ('Security Awareness', 'Data and cyber security training', 2, 'http://lms/sec', 1)")

        faqs = [
            ("What documents do I need on Day 1?", "Please bring Aadhaar card, PAN card, last degree certificate (original + copy), 2 passport photos, and bank account details for salary processing.", "Documents", "document day 1 submit aadhaar pan"),
            ("How do I get my laptop?", "Visit the IT Help Desk on Floor 3 on Day 1 with your employee ID. Your laptop will be pre-configured. Collect it between 9 AM and 11 AM.", "IT Setup", "laptop computer macbook windows it help desk"),
            ("What is the WFH policy for new hires?", "New hires are required to work from office for the first 90 days. After that, WFH is allowed up to 2 days per week with manager approval.", "Policy", "wfh work from home remote policy days"),
            ("Who is my buddy and what do they do?", "Your buddy is an experienced colleague assigned to help you settle in. They will check in with you weekly for the first 3 months. See the Buddy tab for their contact.", "General", "buddy mentor contact help guide"),
            ("How do I apply for leaves?", "You can apply for leaves through the HR Portal. Freshers get 15 days of earned leave pro-rated for the first year.", "Policy", "leave holiday vacation sick days"),
            ("When will I get my ID card?", "Your ID card will be issued by the IT department on Day 1. Ensure you have submitted your passport photo during registration.", "IT Setup", "id card access badge photo")
        ]
        
        app_cursor.executemany(
            "INSERT INTO ONBOARDING_FAQS (question, answer, category, keywords) VALUES (:1, :2, :3, :4)",
            faqs
        )

        app_cursor.execute("INSERT INTO ASSETS (name, serial_number, category, condition, status) VALUES ('ThinkPad T14', 'SN-THNK-001', 'Hardware', 'New', 'Available')")
        app_cursor.execute("INSERT INTO ASSETS (name, serial_number, category, condition, status) VALUES ('MacBook Pro 14', 'SN-MAC-001', 'Hardware', 'Good', 'Available')")
        app_cursor.execute("INSERT INTO ASSETS (name, serial_number, category, condition, status) VALUES ('Dell UltraSharp Monitor', 'SN-MON-001', 'Peripherals', 'New', 'Available')")
        
        app_conn.commit()
        app_cursor.close()
        app_conn.close()

        print("Database schema and seed data created successfully!")

    except Exception as e:
        print(f"Error setting up database: {e}")

if __name__ == '__main__':
    setup_database()
