apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboard-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboard-frontend
  template:
    metadata:
      labels:
        app: onboard-frontend
    spec:
      containers:
        - name: frontend
          image: onboard-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: onboard-frontend-svc
spec:
  selector:
    app: onboard-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
