apiVersion: v1
kind: Secret
metadata:
  name: oracle-credentials
type: Opaque
stringData:
  username: "onboarding_user"
  password: "onboarding123"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  secret-key: "onboard_secret_key_2024_wipro"
  xai-api-key: "eGFpLTdrZXFDRGpyMTdubDdOa0RGanNuYTdjZFZScGFyd1dZeEhYTEEzU0tXS3JKaWhwdzFhNDNURjFMbXdjS0tzcEZIUGhLSEp1UkVBRWtocDdE"
