ALTER SESSION SET CONTAINER = XEPDB1;
BEGIN
   EXECUTE IMMEDIATE 'DROP USER onboarding_user CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/
CREATE USER onboarding_user IDENTIFIED BY onboarding123;
GRANT CONNECT, RESOURCE, DBA TO onboarding_user;
GRANT UNLIMITED TABLESPACE TO onboarding_user;
EXIT;
