import oracledb

c=oracledb.connect(user='onboarding_user', password='onboarding123', dsn='localhost:1521/XEPDB1')
cursor=c.cursor()
try:
    cursor.execute("ALTER TABLE USERS MODIFY user_id GENERATED BY DEFAULT AS IDENTITY (START WITH 2)")
    print("Fixed sequence!")
except Exception as e:
    # If that fails, just insert a dummy user with ID generated and delete it
    try:
        cursor.execute("INSERT INTO USERS (name, email, password_hash) VALUES ('dummy', 'dummy@d.com', 'a')")
        c.commit()
    except:
        pass
    print("Handled sequence by dummy insert")
